ministryofjustice/opg-refunds

caseworker-api/src/App/src/Spreadsheet/PhpSpreadsheetGenerator.php
Add "(GMT)" to the date headers to avoid having to faff with timezones in code.
=> LPA-3211 Add GMT to date headers on spreadsheet export.

Makefile, caseworker-front/src/App/templates/app/sign-in-page.phtml
Add a proper error message for issues caused by CSRF failures.
Also add a new-starter makefile that pulls the externally needed repos this needs to work. Removed everything else from the makefile. This makes the readme correct.
=> LPA-3215 implement content for sign in page time out

caseworker-api/Dockerfile, caseworker-front/Dockerfile, docker-compose.windows.yml, docker-compose.yml, local-sns/Dockerfile, public-front/Dockerfile
Starfox needs to update the base images for the Sirius ECS migration. I've pinned all the refunds version to the latest version in master before our upgrade.
=> Pin Images to current latest version 0.0.318

.pre-commit-config.yaml, docs/runbooks/pre_commit.md, terraform/account/autoscaling_role.tf, terraform/environment/autoscaling_role.tf, terraform/environment/vpc_data_sources.tf
Previous PR, https://github.com/ministryofjustice/opg-refunds/pull/115 sets up autoscaling for ecs. This relies on a service role AWSServiceRoleForApplicationAutoScaling_ECSService, but that role has not been created in preproduction and production accounts.
This PR creates that service role.
Fixes LPA-3440
The service role is created in the terraform/account configuration, and then used in the terraform/environment configuration as a data source.
There appear to be some scenarios where AWS will automatically create and use service roles as part creating other resources in the AWS console.
=> Create and use missing service role for ecs autoscaling

terraform/environment/ecs_caseworker_front.tf, terraform/environment/ecs_public_front.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
Stack type should be relevant to the account
Fixes LPA-3557
set up a tfvar.json entry for the new value per account.
=> Lpa 3557 fix stack type

caseworker-api/config/autoload/envs.global.php, caseworker-api/src/App/src/Service/Spreadsheet.php
_Briefly describe the purpose of the change, and/or link to the JIRA ticket for context_
Fixes LPA-3566
Set the 'delete_after_historical_refund_dates' to 30 by default.
This means 30 days after a refund sop form is submitted the record is made eligible to be deleted.
=> Refunds 3566 set env variable to 30

public-front/config/autoload/envs.global.php, terraform/environment/ecs_public_front.tf, terraform/environment/locals.tf, terraform/environment/terraform.tfvars.json
The ticket is add the env variable for the google analytics tracking id for production only.
Fixes LPA-3559
Added the environment variables for the GA tracking id for the different accounts
=> changes to set the GA tracking id for production account alone

terraform/environment/load_balancer_caseworker_front.tf, terraform/environment/load_balancer_public_front.tf
The ITHC requires the Auditing company access to non-production services.
Fixes LPA-3597
Create a security group rule for each load balancer allowing ingress from BSI's range.
=> add lb sg rule to permit ingress for it health check

terraform/account/locals.tf, terraform/environment/locals.tf
Tags on AWS resources were incorrect
Fixes LPA-3551
update the values for tags in account and environment.
Check terraform plan for account level resources to ensure that no resources would be destroyed during an apply phase
Check terraform plan for environment level resources in preprod and prod to ensure that no resources would be destroyed during an apply phase
=> update resource tags

terraform/account/certificate.tf, terraform/account/lb_access_logs.tf, terraform/account/locals.tf, terraform/account/put_secrets.tf, terraform/account/vpc_endpoints.tf, terraform/account/vpc_flowlogs.tf, terraform/environment/db_cluster_applications.tf, terraform/environment/db_cluster_caseworker.tf, terraform/environment/dynamodb.tf, terraform/environment/ecs_caseworker_api.tf, terraform/environment/ecs_caseworker_front.tf, terraform/environment/ecs_cluster.tf, terraform/environment/ecs_ingestion.tf, terraform/environment/ecs_public_front.tf, terraform/environment/ecs_seeding.tf, terraform/environment/load_balancer_caseworker_front.tf, terraform/environment/load_balancer_public_front.tf, terraform/environment/locals.tf
_add public-front, caseworker and shared as possible tags to AWS resources. The initial purpose of this is to allow us to get costings for the refunds service_
_Updates to terraform tf files to add tags appropriately to all taggable resources. To test that this is done properly , I have verified through the AWS console that examples of all 3 of these tags can be seen_
=> add public-front, caseworker and shared as possible tags

.circleci/config.yml, pipeline_scripts/cancel_previous_jobs/README.md, pipeline_scripts/cancel_previous_jobs/cancel_redundant_builds.py
Improve circle ci efficiency on pr based builds so currently running versions are cancelled at a safe time (not during a terraform apply)
Replicates the cancellation step from UaL to stop any other running jobs on the same pipeline
=> Auto cancel previous jobs

Makefile, README.md, docker-compose.yml
Remove the need for local php file containing secret keys
Fixes LPA-3731
Using the dev environment secrets via aws secret manager within a Makefile and bundle some common tasks in there
=> Lpa 3731 secrets change

public-front/package-lock.json, public-front/package.json
Follow on from Make, fix dependabot vulnerabilities on npm 
Fixes LPAL-168
- npm audit fix, with some manual steps to upgrade dev dependancies.
=> LPAL-168 npm audit fix + manual update of dev dependancies

.circleci/config.yml, docs/pull_request_template.md
Add Docker auth credentials for circleci pipeline.
Fixes LPAL-170
SEE Related PR on Make an LPA for full details: https://github.com/ministryofjustice/opg-lpa/pull/153
=> add auth to docker execution

caseworker-api/composer.json, caseworker-api/composer.lock, caseworker-api/docker/composer/Dockerfile, caseworker-front/composer.json, caseworker-front/composer.lock, caseworker-front/docker/app/Dockerfile, public-front/composer.json, public-front/composer.lock, public-front/docker/app/Dockerfile
This reverts commit f62ea720d6c1c010f30d27f3f872e1edfe2ac68c.
To revert the composer 2 upgrade. 
This somehow broke the spreadsheet functionality. Given age of service and lifecycle of it, i decided to revert rather than investigate a fix.
Fixes LPAL-222
- Revert composer to earlier version
- Pin composer dockerfiles to 1.10
=> LPAL-222 Revert "composer 2 upgrade. (#157)"

terraform/environment/ecs_caseworker_api.tf, terraform/environment/ecs_caseworker_front.tf, terraform/environment/ecs_ingestion.tf, terraform/environment/ecs_seeding.tf
To reduce ECS tasks to minimum sizing for instances (FARGATE Based)
work for LPAL-287
Based on calculations of usage over a period of time, we are reducing sizes of all ECS tasks to minimum where this is not done already. this has been done post public facing access switch off.
- See spreadsheet (MOJ access only): https://docs.google.com/spreadsheets/d/17LewX0ChHEOTkeoHj6db4Jalaz7P2cuNPQlgR5_bjNU/edit?usp=sharing
- https://aws.amazon.com/fargate/pricing/ 
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
=> LPAL-287 reduce sizing of ecs tasks to be minimum.

terraform/environment/ecs_hibernation.tf, terraform/environment/locals.tf
to fix concurrency exception in refunds terraform when creating / modifying ECS autoscale setup.
Relates to LPAL-313
add `depends_on` to hibernation autoscale.
see https://github.com/ministryofjustice/opg-lpa/pull/395
=> add forced dependancies for autoscales

caseworker-api/docker/app/Dockerfile, caseworker-api/docker/ingestion/Dockerfile, caseworker-api/docker/seeding/Dockerfile, caseworker-front/docker/app/Dockerfile, public-front/docker/app/Dockerfile
fix PHP docker versions to 7.4.16, due to issues with later release of PHP 7.4 that has issues with doctrine.
pin dockerfiles.
see  https://bugs.php.net/bug.php?id=81002
=> pin PHP to 7.4.16 - will upgrade when fix available.

docs/runbooks/end-of-life-export/README.md, docs/runbooks/end-of-life-export/export.py, docs/runbooks/end-of-life-export/requirements.txt, terraform/account/export_bucket.tf
Provide an s3 bucket which can be accessed from our moj vpn & dom 1 only so caseworkers can download the resulting spreadsheet securely
The python script fetches claim & payment data from the database, formats it and generates the spreadsheet in A-Z tabbed.
Fixes LPAL-372
Utilise cloud9 access to directly export the data to a spreadsheet and then upload this to the s3 bucket.
=> LPAL-372 Export script & S3 Bucket

terraform/account/archive.tf, terraform/account/lb_access_logs.tf
- To support the export of a snapshot of the caseworker database to S3, in order to archive it.
- Attempt to use intelligent Tiering for the bucket so that archival object will go through the storage tiers automatically.
**Note:** There is no need to archive the applications db as its data is highly transient in nature.
Fixes LPAL-398
- Follow guide on how to export a [RDS snapshot to S3](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html)
- Use intelligent tiering in the bucket
- Exporting RDS snapshot to S3: https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ExportSnapshot.html
- The above being a good jump off point for a number of articles including some listed below.
- Providing access to an Amazon S3 bucket using an IAM …
=> Lpal 398 archive caseworkers db - setup infra

terraform/account/archive.tf, terraform/account/locals.tf
to fix export policy document to remove extraneous prefix.
Fixes LPAL-398
remove `arn:aws:s3:::` as this already gets applied by the reference.
=> LPAL-398: export archive - FIX: remove ARN prefix as not needed in terraform
